### ISSUE TITLE
README.md dosyası yenilenmeli.

### ISSUE THREAD

**Issue by axolotlagatsuma** [TheKralGameOfficial/TheModpackDatabase#1]
POV: Eyüp yeni websiteni yazmayı unutmuştur. Domain bitmiş ama GitHub Pages kullanabilirsin bence.

**Comment by axolotlagatsuma** [comment]
Release olarak Beta 5 var sadece, Beta 6 çıkmamış mıydı?

**Comment by EyuphanMandiraci** [comment]
mpdb.xyz den sonra thempdb.org'a geçtik orda ben website projesine sıfırdan başladım, şu an proje devam etmediği için domainde yok. Beta 5 konusuda ben releaseleri direkt siteye yüklemeye başladım o yüzden burayada güncel değil
